name: redtrajectory
favicon: null
layout_spectrum: 0.49917
typography_spectrum: 0.38898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#251b26'
    - '#584f65'
    - '#a2a8ce'
    - '#d2d6f8'
    - '#d62a47'
  brandStrength: 0.029545619152486324
  lightness: 0.9520104650873691
  saturation: 0.8283928814344108
  rhythmicContrast: 0.33356906846165657
purpose: []
